name: First CICD Pipeline

on: workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic command
        run: echo "Hello from GitHub Actions CI/CD"

      - name: Get current Directory 
        run: pwd


  FileCreation:
    runs-on: ubuntu-latest
    needs: build 

    steps:
       - name: Create New File 
         run: touch file.txt

         

  FileDeletion:
    runs-on: ubuntu-latest
    needs: FileCreation

    steps:
      - name: Deleting file.txt
        run: rm file.txt