name: Self-Hosted Runner 

on: workflow_dispatch 

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic command
        run: echo "Hello from GitHub Actions CI/CD"

      - name: Get current Directory 
        run: pwd


  FileCreation:
    runs-on: ubuntu-latest
    needs: build 

    steps:
       - name: Create New File 
         run: echo "This is File Creation Job"


  FileDeletion:
    runs-on: ubuntu-latest
    needs: FileCreation

    steps:
       - name: Create New File 
         run: echo "This is File Deletion Job"

 